sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pgdevdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pgdevdocker/react-test npm test -- --coverage

after_success:
  - docker build -t pgdevdocker/multi-client ./client
  - docker build -t pgdevdocker/multi-nginx ./nginx
  - docker build -t pgdevdocker/multi-server ./server
  - docker build -t pgdevdocker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pgdevdocker/multi-client
  - docker push pgdevdocker/multi-nginx
  - docker push pgdevdocker/multi-server
  - docker push pgdevdocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-484032209650"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
